accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views  # Importējam visu moduli, lai novērstu ciklus

app_name = 'accounts'

urlpatterns = [
    path('', views.DashboardView.as_view(), name="dashboard"),
    path('members/', views.MembersListView.as_view(), name="members-list"),
    path('<int:pk>/user/', views.ProfileDetailView.as_view(), name='profile-detail'),
    path('<int:pk>/edit/', views.ProfileUpdateView.as_view(), name='profile-update'),
    path('search/', views.global_search, name='global-search'),
    path('password-change/', views.PasswordChangeView.as_view(), name='password-change'),
    
    # Šī rinda piesaista MyLoginView ar Captcha formu
    path('login/', views.MyLoginView.as_view(), name='login'),
    
    path('logout/', auth_views.LogoutView.as_view(next_page='accounts:login'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from .views import (
    ProjectCreateView, 
    ProjectListView, 
    ProjectNearDueDateListView,
    ProjectDetailView,
    KanbanBoardView,
    ProjectDeleteView,
    ProjectUpdateView
    )
from . import views

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name="list"),
    path('create/', ProjectCreateView.as_view(), name="create"),
    path('near-due-date', ProjectNearDueDateListView.as_view(), name="due-list"),
    path('<uuid:pk>', ProjectDetailView.as_view(), name="project-detail"),
    path('<uuid:pk>/delete/', ProjectDeleteView.as_view(), name="delete"),
    path('<uuid:pk>/update/', ProjectUpdateView.as_view(), name="update"),
    path('<uuid:pk>/kanban-board', KanbanBoardView.as_view(), name="kanban-board"),
    path('my-projects/', views.MyProjectsListView.as_view(), name='my-projects'),
    path('archive/projects/', views.archive_projects_list, name='archive-projects'),
    path('comment/<int:pk>/edit/', views.edit_comment, name='edit-comment'),
    path('comment/<int:pk>/delete/', views.delete_comment, name='delete-comment'),
]

swifthub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('accounts.urls', namespace='accounts')),
    path("projects/", include('projects.urls', namespace='projects')),
    path("notifications/", include('notifications.urls', namespace='notifications')),
    path("tasks/", include('tasks.urls', namespace='tasks')),
    path("teams/", include('teams.urls', namespace='teams')),
    
    # authetication
    path('accounts/', include('django.contrib.auth.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from .views import (
    update_task_status_ajax, 
    create_task_ajax, get_task, 
    update_task, 
    assign_user_to_task, 
    get_task_assignment_form
    )
from django.urls import path
from .views import TaskListView, ActiveTaskListView, TaskCreateView, TaskDeleteView
from . import views
from .views import MyActiveTasksListView


app_name = 'tasks'

urlpatterns = [

# 1. Galvenie saraksti un lapas (HTML)
    path('', views.TaskListView.as_view(), name='list'),
    path('active/', views.ActiveTaskListView.as_view(), name='active-tasks'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<uuid:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<uuid:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),

    path('ajax/create/', views.create_task_ajax, name="create-task-ajax"),
    path('ajax/get/<uuid:task_id>/', views.get_task, name="get_task"),
    path('ajax/assign-user/<uuid:task_id>/', views.assign_user_to_task, name="assign-user"),
    path('ajax/assignment-form/<uuid:task_id>/', views.get_task_assignment_form, name="assignment-form"),
    path('update-task-status-ajax/<uuid:task_id>/', views.update_task_status_ajax, name='update-task-status-ajax'),
    path('my-active/', views.MyActiveTasksListView.as_view(), name='my-active-tasks'),
    path('archive/tasks/', views.archive_tasks_list, name='archive-tasks'),

]

accounts/forms.py
from django import forms
from tempus_dominus.widgets import DatePicker
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import AuthenticationForm
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3
from django.conf import settings


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # removing helper text
        self.fields['username'].help_text = None
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None
    

class ProfileUpdateForm(forms.ModelForm):
    education_level = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 3, 'placeholder': "Describe your educational level here ..."}
        ),
        required=True
    )

    skills = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 3, 'placeholder': "Describe your skills here ..."}
        ),
        required=True
    )

    bio = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 3, 'placeholder': "Describe your bior here ..."}
        ),
        required=True
    )

    date_of_birth = forms.DateTimeField(
        label=False,
        required=True,
        widget=DatePicker(
            attrs = {
                'append': 'fa fa-calendar',
                'icon_toggle': True,
            }
        ),
    )
    class Meta:
        model = Profile
        fields = [
            'profile_picture',
            'job_title',
            'education_level',
            'skills',
            'bio',
            'location',
            'phone',
            'date_of_birth'
        ]
        

# class LoginFormWithCaptcha(AuthenticationForm):
#     captcha = ReCaptchaField(widget=ReCaptchaV3())

#     class Media:
#         # Šī rinda automātiski ielādēs Google skriptu jebkurā lapā, kurā ir šī forma
#         # (tai skaitā Admin pieteikšanās lapā)
#         js = ('https://www.google.com/recaptcha/api.js?render=6LcS3j8sAAAAAHOQCbi4c7iQOGHvJMdC8h1oLgRO',)
        

class LoginFormWithCaptcha(AuthenticationForm):
    captcha = ReCaptchaField(widget=ReCaptchaV3())

    @property
    def media(self):
        # 1. Iegūstam bāzes medijus no formas laukiem (piem. recaptcha skriptus)
        base_media = super().media
        
        # 2. Iegūstam atslēgu no settings
        site_key = getattr(settings, "RECAPTCHA_PUBLIC_KEY", "")
        
        # 3. Izveidojam jaunu Media objektu ar mūsu dinamisko skriptu
        custom_js = [f"https://www.google.com/recaptcha/api.js?render={site_key}"]
        dynamic_media = forms.Media(js=custom_js)
        
        # 4. Saskaitām abus Media objektus kopā
        return base_media + dynamic_media

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator
from django.views.generic import View, ListView, DetailView, UpdateView
from django.contrib.auth.decorators import login_not_required
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy, reverse
from projects.models import Project
from tasks.models import Task
from .models import Profile
# from notifications.models import Notifiction 
from teams.models import Team
from .forms import RegisterForm, ProfileUpdateForm
# from comments.models import Comment
from projects.models import Comment
from django.db.models import Q

from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3
from .forms import LoginFormWithCaptcha
from django.conf import settings


# user registration
@login_not_required
def RegisterView(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, "Registration is successful")
            return redirect('login')
        else:
            messages.error(request, "Please correct the errors below")
    else:
        form = RegisterForm()

    return render(request, 'registration/register.html', {'form':form})


class PasswordChangeView(PasswordChangeView):
    template_name = 'registration/password_change_form.html'
    success_url = reverse_lazy('password_change_done')


class DashboardView(View):
    def get(self, request, *args, **kwargs):
        user = request.user
        
        # 1. Datu atlase atkarībā no lietotāja lomas
        if user.is_superuser:
            latest_projects = Project.objects.all()
            latest_tasks = Task.objects.all()
            latest_members = Profile.objects.all()
            team_count = Team.objects.all().count()
        else:
            latest_projects = Project.objects.for_user(user) 
            latest_tasks = Task.objects.for_user(user) 
            latest_members = Profile.objects.filter(
                user__teams__in=user.teams.all()
            ).distinct()
            team_count = user.teams.all().count()

        # 2. Konteksta sagatavošana
        context = {
            "title": "Dashboard",
            "header_text": "Dashboard",
            
            # PAZIŅOJUMI
            # Skaitītājam izmantojam tikai neizlasītos
            "notification_count": user.notifications.unread(user).count(),
            # Sarakstam Dashboard logā izmantojam vēsturi (pēdējos 5)
            "latest_notifications": user.notifications.all().order_by('-created_at')[:5],
            
            # PROJEKTI UN TASKS
            "latest_projects": latest_projects[:5],
            "latest_project_count": latest_projects.count(),
            "projects_near_due_date": latest_projects.due_in_two_days_or_less()[:5],
            "latest_task_count": latest_tasks.count(),
            
            # BIEDRI
            "latest_members": latest_members[:8],
            "latest_member_count": latest_members.count(),
            "team_count": team_count,
        }

        return render(request, "accounts/dashboard.html", context)


class MembersListView(ListView):
    model = Profile
    context_object_name = "members"
    template_name = "accounts/profile_list.html"
    paginate_by = 6

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser:
            latest_members = Profile.objects.all()
            return latest_members
        else:
            latest_members = Profile.objects.filter(
                user__teams__in=user.teams.all()
            ).distinct()
            return latest_members


    def get_context_data(self, **kwargs):
        # latest notifications
        context = super(MembersListView, self).get_context_data(**kwargs)
        # if self.request.user.is_authenticated:
        latest_notifications = self.request.user.notifications.unread(self.request.user)            
        
        context["latest_notifications"] = latest_notifications[:3]
        context["notification_count"] = latest_notifications.count()
        context["header_text"] = "Members"
        context["title"] = "All Members"
        return context
    
class ProfileDetailView(DetailView):
    model = Profile
    template_name = "accounts/profile_detail.html"
    context_object_name = "profile"

    def get_context_data(self, **kwargs):
        profile = self.get_object()
        # latest notifications
        context = super(ProfileDetailView, self).get_context_data(**kwargs)
        # if self.request.user.is_authenticated:
        latest_notifications = self.request.user.notifications.unread(self.request.user)    
        user_projects = Project.objects.for_user(profile.user)  

        # setting pagination for user projects
        paginator = Paginator(user_projects, 3)
        page_number = self.request.GET.get('page')
        page_obj  = paginator.get_page(page_number)

        # setting up  users comment
        user_comments = profile.user.comments.all()
        project_content_type = ContentType.objects.get_for_model(Project)
        project_comments = Comment.objects.filter(
            content_type= project_content_type,
            object_id__in=[str(id) for id in user_projects.values_list('id', flat=True)]            
        )

        # combining comments
        all_user_comments = (user_comments | project_comments).distinct()

         # setting pagination for user comments
        comment_paginator = Paginator(all_user_comments, 5)
        comment_page_number = self.request.GET.get('comment_page')
        comments  = comment_paginator.get_page(comment_page_number)


        #user tasks
        user_tasks = Task.objects.for_user(profile.user)
        task_paginator = Paginator(user_tasks, 5)
        task_page_number = self.request.GET.get('task_page')
        tasks  = task_paginator.get_page(task_page_number)

        context["comments"] = comments
        context["all_user_comments_count"] = all_user_comments.count()
        context["latest_notifications"] = latest_notifications[:3]
        context["notification_count"] = latest_notifications.count()
        context["header_text"] = "Profile"
        context["title"] = f"{profile.full_name}'s Profile"

        # user tasks and project count 
        context["user_tasks_count"] = user_tasks.count()
        context["tasks"] = tasks
        
        context["user_projects_count"] = user_projects.count()
        context["page_obj"] = page_obj
        return context
   

class ProfileUpdateView(UpdateView):
    model = Profile
    form_class = ProfileUpdateForm
    template_name = 'accounts/profile_update.html'

    def get_success_url(self):
        return reverse('accounts:profile-detail', kwargs={'pk': self.request.user.profile.pk})
    
    def get_context_data(self, **kwargs):
        # latest notifications
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        # if self.request.user.is_authenticated:
        latest_notifications = self.request.user.notifications.unread(self.request.user)            
        
        context["latest_notifications"] = latest_notifications[:3]
        context["notification_count"] = latest_notifications.count()
        context["header_text"] = "Update Profile"
        context["title"] = "Update Profile"
        return context

def global_search(request):
    query = request.GET.get('q', '')

    projects = Project.objects.filter(
        Q(name__icontains=query) |
        Q(description__icontains=query)
    ) if query else []

    teams = Team.objects.filter(
        Q(name__icontains=query)
    ) if query else []

    return render(request, 'search/results.html', {
        'query': query,
        'projects': projects,
        'teams': teams,
    })


class MyLoginView(LoginView):
    form_class = LoginFormWithCaptcha  # Jāsakrīt ar importu
    template_name = 'registration/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['RECAPTCHA_PUBLIC_KEY'] = settings.RECAPTCHA_PUBLIC_KEY
        return context
    
class LoginFormWithCaptcha(AuthenticationForm):
    # Pievienojam widget=ReCaptchaV3(), lai aktivizētu v3 versiju
    captcha = ReCaptchaField(widget=ReCaptchaV3())

accounts/templates/accounts/profile_detail.html
{% extends "base.html" %}
{% block title %} {{title }} | {{block.super }}{% endblock %}


{% block content %}

 <div class="container-fluid">
        <div class="row">
          <div class="col-md-3">

            <!-- Profile Image -->
            <div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle"
                       src="{{ profile.profile_picture_url }}"
                       alt="User profile picture">
                </div>

                <h3 class="profile-username text-center">{{ profile.full_name }}</h3>

                <p class="text-muted text-center">{{ profile.job_title}}</p>

                <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item">
                    <b>Projects</b> <a class="float-right">{{ user_projects_count }}</a>
                  </li>
                  <li class="list-group-item">
                    <b>Tasks</b> <a class="float-right">{{ user_tasks_count }}</a>
                  </li>
                </ul>               
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- About Me Box -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">About Me</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <strong><i class="fas fa-book mr-1"></i> Education</strong>

                <p class="text-muted">
                  {{ profile.education_level}}
                </p>

                <hr>

                <strong><i class="fas fa-map-marker-alt mr-1"></i> Location</strong>

                <p class="text-muted">{{ profile.location }}</p>

                <hr>

                <strong><i class="fas fa-pencil-alt mr-1"></i> Skills</strong>

                <p class="text-muted">
                  {{ profile.skills }}
                </p>

                <hr>

                <strong><i class="far fa-file-alt mr-1"></i> Biography</strong>

                <p class="text-muted">{{ profile.bio }}</p>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
          <div class="col-md-9">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Projects</a></li>
                  <li class="nav-item"><a class="nav-link" href="#timeline" data-toggle="tab">Tasks</a></li>
                  
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">
                  <div class="active tab-pane" id="activity">

                     <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 1%">
                          #
                      </th>
                      <th style="width: 20%">
                          Project Name
                      </th>
                      <th style="width: 30%">
                          Team Members
                      </th>
                      <th>
                          Project Progress
                      </th>
                      <th style="width: 8%" class="text-center">
                          Priority
                      </th>
                      <th style="width: 20%">
                      </th>
                  </tr>
              </thead>
              <tbody>

                {% for project in page_obj %}
                  <tr>
                      <td>
                         {{ forloop.counter }}
                      </td>
                      <td>
                          <a href="{% url "projects:project-detail" project.id %}">
                              {{ project.name }}
                          </a>
                          <br/>
                          <small>
                              Created {{ project.start_date }}
                          </small>
                      </td>
                      <td>
                          <ul class="list-inline">
                            {% for member in project.team.members.all %}
                              <li class="list-inline-item">
                                  <img alt="Avatar" class="table-avatar" src="{{ member.profile.profile_picture_url }}">
                              </li>
                              {% endfor %}
                              
                          </ul>
                      </td>
                      <td class="project_progress">
                          <div class="progress progress-sm">
                              <div class="progress-bar bg-{{project.status_color}}" role="progressbar" aria-valuenow="{{ project.progress}}" aria-valuemin="0" aria-valuemax="100" style="width: {{project.progress}}%">
                              </div>
                          </div>
                          <small>
                            {{ project.progress}}% Complete
                          </small>
                      </td>
                      <td class="project-state">
                          <span class="badge badge-{{ project.priority_color }}">{{ project.priority }}</span>
                      </td>
                      <td class="project-actions text-right">
                         
                        {% if request.user == project.owner %}
                          <a href="{% url "projects:update" project.pk %}" class="btn btn-info btn-sm" href="#">
                              <i class="fas fa-pencil-alt">
                              </i>
                              Edit
                          </a>

                          
                           <a href="{% url "projects:delete" project.pk %}" class="btn btn-danger btn-sm" href="#">
                              <i class="fas fa-trash">
                              </i>
                              Delete
                          </a>
                          {% endif %}
                         
                      </td>
                  </tr>

                  {% endfor %}



              </tbody>
          </table>

       {% include "components/paginator.html" %}


        {% comment %} displaying messages {% endcomment %}
            {% if messages %}
            <div class="messages col-10">
              {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{message.tags}}{% else %}alert-info{% endif %}">
                {{ message }}
              </div>
              
              {% endfor %}

            </div>
            
            {% endif %}

       


        </div>
        <!-- /.card-body -->
                  
                    <!-- /.post -->
                  </div>


                  <!-- /.tab-pane -->
                  <div class="tab-pane" id="timeline">

                      <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 1%">
                          #
                      </th>
                      <th style="width: 20%">
                          Task Name
                      </th>
                      <th style="width: 30%">
                          Team Members
                      </th>
                      <th>
                          Task Progress
                      </th>
                      <th style="width: 8%" class="text-center">
                          Priority
                      </th>
                      <th style="width: 20%">
                      </th>
                  </tr>
              </thead>
              <tbody>

                {% for task in tasks %}
                  <tr>
                      <td>
                         {{ forloop.counter }}
                      </td>
                      <td>
                          <a href="">
                              {{ task.name }}
                          </a>
                          <br/>
                          <small>
                              Created {{ task.created_at }}
                          </small>
                      </td>
                      <td>
                          <ul class="list-inline">
                            {% for member in task.project.team.members.all %}
                              <li class="list-inline-item">
                                  <img alt="Avatar" class="table-avatar" src="{{ member.profile.profile_picture_url }}">
                              </li>
                              {% endfor %}
                              
                          </ul>
                      </td>
                      <td class="project_progress">
                          <div class="progress progress-sm">
                              <div class="progress-bar bg-{{task.status_color}}" role="progressbar" aria-valuenow="{{ task.progress}}" aria-valuemin="0" aria-valuemax="100" style="width: {{task.progress}}%">
                              </div>
                          </div>
                          <small>
                            {{ task.progress}}% Complete
                          </small>
                      </td>
                      <td class="project-state">
                          <span class="badge badge-{{ task.priority_color }}">{{ task.priority }}</span>
                      </td>
                    
                  </tr>

                  {% endfor %}



              </tbody>
          </table>

       {% include "components/paginator.html" %}


       


        </div>

                    
                  </div>
                  <!-- /.tab-pane -->

                 
                </div>
                <!-- /.tab-content -->
                 <hr>
                 <br>
                 <h2 class="card-title">Comments {{ all_user_comments_count }}</h2>
                  <br>
                   <br>

                 <!-- comments start here -->
                  {% for comment in  comments %}
                    <!-- Comment -->
                    <div class="post">
                      <div class="user-block">
                        <img class="img-circle img-bordered-sm" src="{{ comment.user.profile.profile_picture_url}}" alt="user image">
                        <span class="username">
                          <a href="#">{{ comment.user.profile.full_name }}</a>
                          <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>
                        </span>
                        <span class="description">Shared publicly - {{ comment.created_at | timesince }}</span>
                      </div>
                      <!-- /.user-block -->
                      <p>
                       {{ comment.comment }}
                      </p>

                    </div>
                    <!-- /.post -->
                     {% endfor %}

                      {% include "comments/comment_paginator.html" %}


              </div><!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->

{% endblock %}

accounts/templates/accounts/profile_list.html
{% extends "base.html" %}
{% block title %} {{title }} | {{block.super }}{% endblock %}


{% block content %}

 <!-- Default box -->
 <div class="card card-solid">
    <div class="card-body pb-0">
      <div class="row">

        {% for member in members %}
        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch flex-column">
          <div class="card bg-light d-flex flex-fill">
            <div class="card-header text-muted border-bottom-0">
             {{ member.job_title }}
            </div>
            <div class="card-body pt-0">
              <div class="row">
                <div class="col-7">
                  <h2 class="lead"><b>{{ member.full_name }}</b></h2>
                  <p class="text-muted text-sm"><b>About: </b> {{ member.bio }} </p>
                  <ul class="ml-4 mb-0 fa-ul text-muted">
                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: {{ member.location }}</li>
                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: {{ member.phone }}</li>
                  </ul>
                </div>
                <div class="col-5 text-center">
                  <img src="{{ member.profile_picture_url }}" alt="user-avatar" class="img-circle img-fluid">
                </div>
              </div>
            </div>
            <div class="card-footer">
              <div class="text-right">
                
                <a href="{% url "accounts:profile-detail" member.pk %}" class="btn btn-sm btn-primary">
                  <i class="fas fa-user"></i> View Profile
                </a>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

       


      
      </div>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
        {% include "components/paginator.html" %}
    </div>
    <!-- /.card-footer -->
  </div>
  <!-- /.card -->


{% endblock  %}

accounts/templates/accounts/profile_update.html
{% extends "base.html" %}
{% block title %} {{title }} | {{block.super }}{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<!-- <form method="post" entype="multipart/form-data"> -->
<form method="post" enctype="multipart/form-data"></form>
    {% csrf_token %}
<div class="row">
    <div class="col-md-6">
        {% comment %} {{ form.as_p }} {% endcomment %}
       <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Update Profile</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          <div class="form-group">
            {{ form|crispy }}
           
          </div>
         
         
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>

    
    
  </div>
  <div class="row">
    <div class="col-md-6">
      <a href="{% url "accounts:dashboard" %}" class="btn btn-secondary">Cancel</a>
      <input type="submit" value="Save Changes" class="btn btn-success float-right">
    </div>
  </div>
</form>

{% endblock  %}