projects/urls.py
from django.urls import path
from .views import (
    ProjectCreateView, 
    ProjectListView, 
    ProjectNearDueDateListView,
    ProjectDetailView,
    KanbanBoardView,
    ProjectDeleteView,
    ProjectUpdateView
    )
from . import views

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name="list"),
    path('create/', ProjectCreateView.as_view(), name="create"),
    path('near-due-date', ProjectNearDueDateListView.as_view(), name="due-list"),
    path('<uuid:pk>', ProjectDetailView.as_view(), name="project-detail"),
    path('<uuid:pk>/delete/', ProjectDeleteView.as_view(), name="delete"),
    path('<uuid:pk>/update/', ProjectUpdateView.as_view(), name="update"),
    path('<uuid:pk>/kanban-board', KanbanBoardView.as_view(), name="kanban-board"),
    path('my-projects/', views.MyProjectsListView.as_view(), name='my-projects'),
    path('archive/projects/', views.archive_projects_list, name='archive-projects'),
    path('comment/<int:pk>/edit/', views.edit_comment, name='edit-comment'),
    path('comment/<int:pk>/delete/', views.delete_comment, name='delete-comment'),
]

swifthub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('accounts.urls', namespace='accounts')),
    path("projects/", include('projects.urls', namespace='projects')),
    path("notifications/", include('notifications.urls', namespace='notifications')),
    path("tasks/", include('tasks.urls', namespace='tasks')),
    path("teams/", include('teams.urls', namespace='teams')),
    
    # authetication
    path('accounts/', include('django.contrib.auth.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from .views import (
    update_task_status_ajax, 
    create_task_ajax, get_task, 
    update_task, 
    assign_user_to_task, 
    get_task_assignment_form
    )
from django.urls import path
from .views import TaskListView, ActiveTaskListView, TaskCreateView, TaskDeleteView
from . import views
from .views import MyActiveTasksListView


app_name = 'tasks'

urlpatterns = [

# 1. Galvenie saraksti un lapas (HTML)
    path('', views.TaskListView.as_view(), name='list'),
    path('active/', views.ActiveTaskListView.as_view(), name='active-tasks'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<uuid:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<uuid:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),

    path('ajax/create/', views.create_task_ajax, name="create-task-ajax"),
    path('ajax/get/<uuid:task_id>/', views.get_task, name="get_task"),
    path('ajax/assign-user/<uuid:task_id>/', views.assign_user_to_task, name="assign-user"),
    path('ajax/assignment-form/<uuid:task_id>/', views.get_task_assignment_form, name="assignment-form"),
    path('update-task-status-ajax/<uuid:task_id>/', views.update_task_status_ajax, name='update-task-status-ajax'),
    path('my-active/', views.MyActiveTasksListView.as_view(), name='my-active-tasks'),
    path('archive/tasks/', views.archive_tasks_list, name='archive-tasks'),

]

projects/forms.py
from django import forms
# from django.contrib.auth.models import User
from tempus_dominus.widgets import DatePicker
from .models import Project, Attachment
from teams.models import Team
from .utils import STATUS_CHOICES, PRIORITY_CHOICES


class ProjectForm(forms.ModelForm):
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 3, 'placeholder': "Describe your project here ..."}
        ),
        label=False,
        # required=True
        required=False
    )

    name = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': "Enter the name of your project here ..."}
        ),
        required=True,
        label=False
    )

    team = forms.ModelChoiceField(
        queryset=Team.objects.all(),
        widget=forms.Select(
            attrs={'class': "form-control"}
        ),
        label=False,
        required=True
    )

    client_company = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': "Client company name (optional)"}
        ),
        required=False,  # ŠIS IR SVARĪGĀKAIS
        label=False      # Ja izmanto savu labelu HTML pusē
    )

    status = forms.ChoiceField(
        choices=STATUS_CHOICES,
        widget=forms.Select(
            attrs={'class': "form-control"}
        ),
        label=False,
        required=True
    )

    priority = forms.ChoiceField(
        choices=PRIORITY_CHOICES,
        widget=forms.Select(
            attrs={'class': "form-control"}
        ),
        label=False,
        required=True
    )

    start_date = forms.DateTimeField(
        label=False,
        required=True,
        widget=DatePicker(
            attrs={
                'append': 'fa fa-calendar',
                'icon_toggle': True,
            }
        ),
    )

    due_date = forms.DateTimeField(
        label=False,
        required=True,
        widget=DatePicker(
            attrs={
                'append': 'fa fa-calendar',
                'icon_toggle': True,
            }
        ),
    )

    total_amount = forms.DecimalField(
        label=False,
        required=False
    )

    amount_spent = forms.DecimalField(
        label=False,
        required=False
    )

    estimated_duration = forms.DecimalField(
        label=False,
        required=False
    )

    class Meta:
        model = Project
        fields = [
            "name",
            "team",
            "client_company",
            "description",
            "status",
            "priority",
            "start_date",
            "due_date",
            "total_amount",
            "amount_spent",
            "estimated_duration"
        ]


class AttachmentForm(forms.ModelForm):
    class Meta:
        model = Attachment
        fields = ['file']

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.contrib import messages
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from .models import Project
from .forms import ProjectForm, AttachmentForm
# from comments.models import Comment
from .models import Comment
from comments.forms import CommentForm
from tasks.forms import TaskUpdateForm
from notifications.tasks import create_notification
from django.db.models import Q, CharField
from django.db.models.functions import Cast
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.conf import settings
from django.utils import timezone
from django.http import HttpResponseForbidden
from .models import Comment  


class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectForm
    template_name = 'projects/project_create_and_update.html'
    success_url = reverse_lazy('projects:list')

    # ... get_context_data paliek nemainīts ...

    def form_valid(self, form):
        # 1. Piesaistām īpašnieku
        form.instance.owner = self.request.user
        
        # 2. Saglabājam projektu datubāzē
        response = super().form_valid(form)
        
        # 3. Izsaucam paziņojumu sistēmu
        # Šī funkcija automātiski nosūtīs VIENU glītu HTML e-pastu
        create_notification(
            actor_username=self.request.user.username,
            verb=f'Jauns projekts: {self.object.name}',
            object_id=self.object.id,
            content_type_model="project",
            content_type_app_label="projects"
        )
        
        # VISU TRY/EXCEPT BLOKU AR SEND_MAIL ŠEIT VAJAG IZDZĒST
        
        return response
    

class ProjectListView(ListView):
    model = Project
    context_object_name = "projects"
    template_name = "projects/project_list.html"
    paginate_by = 5

def get_queryset(self):
    # 1. Pamata queryset - atļaujam gan īpašniekam, gan komandas biedriem
    # Pārliecinies, ka Q ir importēts (from django.db.models import Q)
    queryset = Project.objects.filter(
        Q(owner=self.request.user) | Q(team__members=self.request.user)
    ).distinct()
    
    query = self.request.GET.get('q')
    
    if query:
        parsed_date = None
        try:
            parsed_date = datetime.strptime(query, "%d.%m.%Y").strftime("%Y-%m-%d")
        except ValueError:
            pass

        # Filtrējam jau paplašināto queryset
        queryset = queryset.annotate(
            due_date_str=Cast('due_date', CharField())
        ).filter(
            Q(name__icontains=query) | 
            Q(description__icontains=query) |
            Q(due_date_str__icontains=query)
        )

        if parsed_date:
            # Pievienojam datuma sakritību, saglabājot piekļuves tiesības
            date_queryset = Project.objects.filter(
                Q(owner=self.request.user) | Q(team__members=self.request.user),
                due_date=parsed_date
            )
            queryset |= date_queryset

    return queryset.distinct().order_by('-created_at')


class MyProjectsListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = 'projects/project_list.html' # Izmantojam esošo projektu saraksta veidni
    context_object_name = 'projects'

    def get_queryset(self):
        # Atlasa projektus, kur:
        # 1. Lietotājs ir īpašnieks (owner)
        # VAI
        # 2. Lietotājs ir projektam piesaistītajā komandā
        return Project.objects.filter(
            Q(owner=self.request.user) | Q(team__members=self.request.user)
        ).distinct().order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "My projects"
        # context['header_text'] = "My projects"
        return context

def get_context_data(self, **kwargs):
    context = super(ProjectListView, self).get_context_data(**kwargs)
    # Saglabājam paziņojumu loģiku
    latest_notifications = self.request.user.notifications.unread(self.request.user)
    context["latest_notifications"] = latest_notifications[:3]
    context["notification_count"] = latest_notifications.count()
    
    # Saglabājam meklēšanas vārdu formā
    context["search_query"] = self.request.GET.get('q', '')
    
    context["header_text"] = "Projects"
    context["title"] = "All Projects"
    return context

class ProjectNearDueDateListView(ListView):
    model = Project
    context_object_name = "projects"
    template_name = "projects/project_list.html"
    paginate_by = 5

    def get_queryset(self):
        return Project.objects.for_user(self.request.user).due_in_two_days_or_less()

    def get_context_data(self, **kwargs):
        # latest notifications
        context = super(ProjectNearDueDateListView,
                        self).get_context_data(**kwargs)
        # if self.request.user.is_authenticated:
        latest_notifications = self.request.user.notifications.unread(
            self.request.user)

        context["latest_notifications"] = latest_notifications[:3]
        context["notification_count"] = latest_notifications.count()
        context["header_text"] = "Due Projects"
        return context

class ProjectUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'projects/project_create_and_update.html'

    def get_object(self, queryset=None):
        # Tikai iegūstam objektu. Piekļuvi pārbaudīs test_func.
        return get_object_or_404(Project, pk=self.kwargs['pk'])

    def test_func(self):
        # Šeit notiek galvenā piekļuves pārbaude (Īpašnieks vai Admin)
        project = self.get_object()
        return self.request.user == project.owner or self.request.user.is_superuser

    def handle_no_permission(self):
        # Ja test_func atgriež False, lietotājs tiek novirzīts ar paziņojumu
        messages.error(self.request, "Jums nav tiesību labot šo projektu!")
        return redirect('projects:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Paziņojumu loģika
        if self.request.user.is_authenticated:
            # Pārliecinies, vai .unread() tiešām prasa lietotāju kā argumentu
            latest_notifications = self.request.user.notifications.unread(self.request.user)
            context["latest_notifications"] = latest_notifications[:3]
            context["notification_count"] = latest_notifications.count()
        
        context.update({
            "header_text": "Project Edit",
            "title": "Project Edit",
            "button_text": "Save changes"
        })
        return context

    def form_valid(self, form):
        messages.success(self.request, "Project updated successfully")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Please correct the errors and try again.")
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse_lazy('projects:project-detail', kwargs={'pk': self.object.pk})


class ProjectDeleteView(DeleteView):
    model = Project
    template_name = 'projects/confirm_delete.html'
    success_url = reverse_lazy('projects:list')

    def get_object(self, queryset=None):
        # get project
        project = get_object_or_404(Project, pk=self.kwargs['pk'])

        # check permission on this project
        if project.owner != self.request.user:
            raise Http404("Project not found.")
        return project

    def get_context_data(self, **kwargs):
        # latest notifications
        context = super(ProjectDeleteView, self).get_context_data(**kwargs)
        # if self.request.user.is_authenticated:
        latest_notifications = self.request.user.notifications.unread(
            self.request.user)

        context["latest_notifications"] = latest_notifications[:3]
        context["notification_count"] = latest_notifications.count()
        context["header_text"] = "Delete Project"
        return context

    def post(self, request, *args, **kwargs):
        # get project and check permissions
        project = self.get_object()

        messages.success(
            request, f"The project {project.name} is deleted successfully.")
        return super().post(request, *args, **kwargs)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = 'projects/project_detail.html'
    context_object_name = 'project' # Labāka prakse template piekļuvei

    def get_queryset(self):
        # Šis filtrē, kurus objektus lietotājs vispār drīkst redzēt
        from django.db.models import Q
        return Project.objects.filter(
            Q(owner=self.request.user) | Q(team__members=self.request.user)
        ).select_related('owner').prefetch_related('team__members').distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Izmantojam jau ielādēto objektu
        project = self.object 
        
        # Paziņojumi (pārliecinies, ka models.py ir salabots, kā runājām sākumā)
        unread_notifications = self.request.user.notifications.filter(read=False)

        comments = Comment.objects.filter_by_instance(project)
        paginator = Paginator(comments, 5)
        page_number = self.request.GET.get('page')
        
        context.update({
            "latest_notifications": unread_notifications[:3],
            "notification_count": unread_notifications.count(),
            "title": project.name,
            "page_obj": paginator.get_page(page_number),
            "comments_count": comments.count(),
            "comment_form": CommentForm(),

projects/templates/projects/archive_projects.html
{% extends "base.html" %}
{% block title %} {{ title }} | {{ block.super }}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h3 class="card-title text-danger"><i class="fas fa-history"></i> Archived Projects (Expired)</h3>
    </div>
    <div class="card-body p-0">
        <table class="table table-striped projects">
            <thead>
                <tr>
                    <th>Project Name</th>
                    <th>Deadline</th>
                    <th>Status</th>
                    <th style="width: 20%"></th>
                </tr>
            </thead>
            <tbody>
                {% for project in projects %}
                <tr>
                    <td>
                        <a>{{ project.name }}</a>
                        <br/>
                        <small>Created {{ project.created_at|date:"d.m.Y" }}</small>
                    </td>
                    <td>
                        <span class="badge badge-danger">{{ project.due_date|date:"d.m.Y" }}</span>
                    </td>
                    <td>
                        <span class="badge badge-secondary">{{ project.status }}</span>
                    </td>
                    <td class="project-actions text-right">
                        <a class="btn btn-primary btn-sm" href="{% url 'projects:project-detail' project.pk %}">
                            <i class="fas fa-folder"></i> View
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4" class="text-center text-muted py-4">No archived projects found.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

projects/templates/projects/confirm_delete.html
{% extends "base.html" %}


{% block content %}
<h2>Confirm Deletion</h2>

<p>Are you sure you want to delete the project "{{ project.name }}"?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url "projects:list" %}" class="btn btn-secondary">Cancel</a>
</form>

{% endblock %}

projects/templates/projects/project_detail.html
{% extends "base.html" %}
{% block title %}{{title }} |{{block.super}}{% endblock title %}
{% load crispy_forms_tags %}

{% block content %}

 <!-- Default box -->
 <div class="card">
    <div class="card-header">
      <!-- <h3 class="card-title">{{ project.name }}</h3> -->
       <h3 class="card-title">
          {{ project.name }}
          {% if project.owner == request.user or request.user.is_superuser %}
              <span class="ml-2">
                  <a href="{% url 'projects:update' project.pk %}" class="btn btn-xs btn-info">
                      <i class="fas fa-edit"></i> Edit
                  </a>
                  <a href="{% url 'projects:delete' project.pk %}" class="btn btn-xs btn-danger">
                      <i class="fas fa-trash"></i> Delete
                  </a>
              </span>
          {% endif %}
      </h3>

      <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
          <i class="fas fa-minus"></i>
        </button>
        <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
          <i class="fas fa-times"></i>
        </button>
      </div>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
          <div class="row">
            <div class="col-12 col-sm-4">
              <div class="info-box bg-light">
                <div class="info-box-content">
                  <span class="info-box-text text-center text-muted">Estimated budget</span>
                  <span class="info-box-number text-center text-muted mb-0">{% if project.total_amount %}{{ project.total_amount }} {% else %}0{% endif %}</span>
                </div>
              </div>
            </div>
            <div class="col-12 col-sm-4">
              <div class="info-box bg-light">
                <div class="info-box-content">
                  <span class="info-box-text text-center text-muted">Total amount spent</span>
                  <span class="info-box-number text-center text-muted mb-0">{% if project.amount_spent %}{{ project.amount_spent }} {% else %}0{% endif %}</span>
                </div>
              </div>
            </div>
            <div class="col-12 col-sm-4">
              <div class="info-box bg-light">
                <div class="info-box-content">
                  <span class="info-box-text text-center text-muted">Estimated project duration</span>
                  <span class="info-box-number text-center text-muted mb-0">{% if project.estimated_duration %}{{ project.estimated_duration }} Days {% else %}0{% endif %}</span>
                </div>
              </div>
            </div>
          </div>

          <br> 
          <!-- project kanban board -->
          <a href="{% url "projects:kanban-board" project.id %}" class="btn btn-sm btn-primary">View Kanban Board</a> 
           <!-- end of project kanban board -->               
              
            <br>
            <br>

            
  <!-- comments -->      
          <div class="row">
            <div class="col-12">
              <h4>Recent Comments({{ comments_count }})</h4>
            <form action="{% url "projects:project-detail" project.pk %}" method="post">
              {% csrf_token %}
              <div class="col-10">
              {{ comment_form|crispy }}
            </div>

            {% comment %} button {% endcomment %}
            <div class="row">
              <div class="col-10">
                <input type="submit" name="comment_submit" value="post your comment" class="btn btn-success float-left">
              </div>
            </div>
            </form>
            <br>
            {% comment %} displaying messages {% endcomment %}
            {% if messages %}
            <div class="messages col-10">
              {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{message.tags}}{% else %}alert-info{% endif %}">
                {{ message }}
              </div>
              
              {% endfor %}

            </div>
            
            {% endif %}

            {% for comment in page_obj %}
            <div class="post" id="comment-{{ comment.id }}">
                <div class="user-block">
                    <img class="img-circle img-bordered-sm" src="{{ comment.user.profile.profile_picture_url }}" alt="user image">
                    <span class="username">
                        <a href="#">{{ comment.user.profile.full_name }}</a>
                        
                        {# Rādām darbību pogas tikai autoram vai adminam #}
                        {% if comment.user == request.user or request.user.is_superuser %}
                        <span class="float-right">
                            <button type="button" class="btn btn-tool" onclick="toggleEdit('{{ comment.id }}')">
                                <i class="fas fa-pencil-alt text-info"></i>
                            </button>
                            
                            <form action="{% url 'projects:delete-comment' comment.id %}" method="post" style="display: inline;" onsubmit="return confirm('Are you sure you want to delete this comment?')">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-tool">
                                    <i class="fas fa-times text-danger"></i>
                                </button>
                            </form>
                        </span>
                        {% endif %}
                    </span>
                    <span class="description">Pievienots: {{ comment.created_at|timesince }} atpakaļ</span>
                </div>

                <div id="comment-text-{{ comment.id }}">
                    <p>{{ comment.comment }}</p>
                </div>

                {% if comment.user == request.user or request.user.is_superuser %}
                <div id="edit-form-{{ comment.id }}" style="display: none; margin-bottom: 15px;">
                    <form action="{% url 'projects:edit-comment' comment.id %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <textarea name="comment_text" class="form-control" rows="2">{{ comment.comment }}</textarea>
                        </div>
                        <button type="submit" class="btn btn-sm btn-success">Saglabāt</button>
                        <button type="button" class="btn btn-sm btn-secondary" onclick="toggleEdit('{{ comment.id }}')">Atcelt</button>
                    </form>
                </div>
                {% endif %}
            </div>
            {% empty %}
            <p class="text-muted">Vēl nav neviena komentāra.</p>
            {% endfor %}
            

            <!-- {% for comment in page_obj %}
                <div class="post">
                  <div class="user-block">
                    <img class="img-circle img-bordered-sm" src="{{ comment.user.profile.profile_picture_url }}" alt="user image">
                    <span class="username">
                      <a href="#">{{ comment.user.profile.full_name }}</a>
                    </span>
                    <span class="description">Shared publicly - {{ comment.created_at | timesince}}</span>
                  </div>
                  
                  <p>
                    {{ comment.comment }}
                  </p>                  
                </div>

                {% endfor %}                -->
            </div>
          </div>
        {% comment %} pagination {% endcomment %}
        {% include "components/paginator.html" %}

        </div>
        <div class="col-12 col-md-12 col-lg-4 order-1 order-md-2">
          <h3 class="text-primary"><i class="fas fa-paint-brush"></i> {{ my_company }}</h3>
          <p class="text-muted">{{ my_company_description }}</p>
          <br>
          <div class="text-muted">
            {% if project.client_company %}
            <p class="text-sm">Client Company
              <b class="d-block">{{ project.client_company }}</b>
            </p>
            {% endif %}
            <p class="text-sm">Project Leader
              <b class="d-block">{{ project.team.team_lead.profile.full_name }}</b>
            </p>
          </div>

          <h5 class="mt-5 text-muted">Project files</h5>
          <ul class="list-unstyled">
            {% for attachment in project.attachments.all %}
            <li>
              <a href="{{ attachment.file.url }}"  target="_blank"  class="btn-link text-secondary">
                <i class="far fa-fw fa-file"></i> {{ attachment.file.name|truncatechars:40 }}x</a>
            </li>
            {% endfor %}
           
          </ul>
          <div class="text-center mt-5 mb-3">
            <button type="button" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#modal-default">
             Add files
            </button>
            
          </div>
        </div>
      </div>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->

  <div class="modal fade" id="modal-default">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Upload project files</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
        <div class="modal-body">
          {{ attachment_form }}
        </div>
        <div class="modal-footer justify-content-between">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <input type="submit" name="attachment_submit" value="Upload file" class="btn btn-primary">
        </div>
      </form>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>
  <!-- /.modal -->

{% endblock %}
{% block script %}
<script>
function toggleEdit(commentId) {
    const textDiv = document.getElementById('comment-text-' + commentId);
    const formDiv = document.getElementById('edit-form-' + commentId);

    if (formDiv.style.display === "none") {
        textDiv.style.display = "none";
        formDiv.style.display = "block";
    } else {
        textDiv.style.display = "block";
        formDiv.style.display = "none";
    }
}
</script>
{% endblock %}