accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views  # Importējam visu moduli, lai novērstu ciklus

app_name = 'accounts'

urlpatterns = [
    path('', views.DashboardView.as_view(), name="dashboard"),
    path('members/', views.MembersListView.as_view(), name="members-list"),
    path('<int:pk>/user/', views.ProfileDetailView.as_view(), name='profile-detail'),
    path('<int:pk>/edit/', views.ProfileUpdateView.as_view(), name='profile-update'),
    path('search/', views.global_search, name='global-search'),
    path('password-change/', views.PasswordChangeView.as_view(), name='password-change'),
    
    # Šī rinda piesaista MyLoginView ar Captcha formu
    path('login/', views.MyLoginView.as_view(), name='login'),
    
    path('logout/', auth_views.LogoutView.as_view(next_page='accounts:login'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/urls.py
from django.urls import path
from .views import NotificationListView, MarkNotificationAsRead
from . import views

app_name = 'notifications'

urlpatterns = [
    path('', NotificationListView.as_view(), name="notification-list"),
    path('<int:notification_id>/read/', MarkNotificationAsRead.as_view(), name="mark_as_read"),
    path('unread-count/', views.unread_notifications_count, name='unread-count'),
]

projects/urls.py
from django.urls import path
from .views import (
    ProjectCreateView, 
    ProjectListView, 
    ProjectNearDueDateListView,
    ProjectDetailView,
    KanbanBoardView,
    ProjectDeleteView,
    ProjectUpdateView
    )
from . import views

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name="list"),
    path('create/', ProjectCreateView.as_view(), name="create"),
    path('near-due-date', ProjectNearDueDateListView.as_view(), name="due-list"),
    path('<uuid:pk>', ProjectDetailView.as_view(), name="project-detail"),
    path('<uuid:pk>/delete/', ProjectDeleteView.as_view(), name="delete"),
    path('<uuid:pk>/update/', ProjectUpdateView.as_view(), name="update"),
    path('<uuid:pk>/kanban-board', KanbanBoardView.as_view(), name="kanban-board"),
    path('my-projects/', views.MyProjectsListView.as_view(), name='my-projects'),
    path('archive/projects/', views.archive_projects_list, name='archive-projects'),
    path('comment/<int:pk>/edit/', views.edit_comment, name='edit-comment'),
    path('comment/<int:pk>/delete/', views.delete_comment, name='delete-comment'),
]

swifthub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('accounts.urls', namespace='accounts')),
    path("projects/", include('projects.urls', namespace='projects')),
    path("notifications/", include('notifications.urls', namespace='notifications')),
    path("tasks/", include('tasks.urls', namespace='tasks')),
    path("teams/", include('teams.urls', namespace='teams')),
    
    # authetication
    path('accounts/', include('django.contrib.auth.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from .views import (
    update_task_status_ajax, 
    create_task_ajax, get_task, 
    update_task, 
    assign_user_to_task, 
    get_task_assignment_form
    )
from django.urls import path
from .views import TaskListView, ActiveTaskListView, TaskCreateView, TaskDeleteView
from . import views
from .views import MyActiveTasksListView


app_name = 'tasks'

urlpatterns = [

# 1. Galvenie saraksti un lapas (HTML)
    path('', views.TaskListView.as_view(), name='list'),
    path('active/', views.ActiveTaskListView.as_view(), name='active-tasks'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<uuid:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<uuid:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),

    path('ajax/create/', views.create_task_ajax, name="create-task-ajax"),
    path('ajax/get/<uuid:task_id>/', views.get_task, name="get_task"),
    path('ajax/assign-user/<uuid:task_id>/', views.assign_user_to_task, name="assign-user"),
    path('ajax/assignment-form/<uuid:task_id>/', views.get_task_assignment_form, name="assignment-form"),
    path('update-task-status-ajax/<uuid:task_id>/', views.update_task_status_ajax, name='update-task-status-ajax'),
    path('my-active/', views.MyActiveTasksListView.as_view(), name='my-active-tasks'),
    path('archive/tasks/', views.archive_tasks_list, name='archive-tasks'),

]

teams/urls.py
from django.urls import path
from .views import TeamCreateView, TeamListView, TeamUpdateView, TeamDeleteView
from . import views

app_name = 'teams'

urlpatterns = [
    path('', TeamListView.as_view(), name="team-list"),
    path('create/', TeamCreateView.as_view(), name="team-create"),
    path('<int:pk>/update/', TeamUpdateView.as_view(), name="team-update"),
    path('<int:pk>/delete/', TeamDeleteView.as_view(), name="team-delete"),
    path('my-teams/', views.MyTeamsListView.as_view(), name='my-teams'),
]

templates/components/css.html
{% load static %}


<!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static "plugins/fontawesome-free/css/all.min.css" %} ">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static "plugins/overlayScrollbars/css/OverlayScrollbars.min.css" %} ">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "dist/css/adminlte.min.css" %} ">

templates/components/footer.html
<footer class="main-footer">
    <strong>Copyright &copy; 2026 Wolf</strong>
    <!-- <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.2.0
    </div> -->
  </footer>

templates/components/header_content.html
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">{{ header_text }}</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">{{ header_text }}</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>

templates/components/javascript.html
{% load static %}


<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
<!-- Bootstrap -->
<script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- overlayScrollbars -->
<script src="{% static "plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "dist/js/adminlte.js" %}"></script>

<!-- PAGE PLUGINS -->
<!-- jQuery Mapael -->
<script src="{% static "plugins/jquery-mousewheel/jquery.mousewheel.js" %}"></script>
<script src="{% static "plugins/raphael/raphael.min.js" %}"></script>
<script src="{% static "plugins/jquery-mapael/jquery.mapael.min.js" %}"></script>
<!-- <script src="plugins/jquery-mapael/maps/usa_states.min.js"></script> -->
<script src="{% static "plugins/jquery-mapael/maps/usa_states.min.js" %}"></script>
<!-- ChartJS -->
<script src="{% static "plugins/chart.js/Chart.min.js" %}"></script>

<!-- AdminLTE for demo purposes -->
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{% comment %} <script src="{% static "dist/js/pages/dashboard2.js" %}"></script> {% endcomment %}

templates/components/navbar.html
<nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <!-- <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'accounts:dashboard' %}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'projects:list' %}" class="nav-link">Projects</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'teams:team-list' %}" class="nav-link">Teams</a>
      </li>
    </ul> -->

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">

      
      <!-- Navbar Search -->
      <form class="form-inline" method="get" action="{% url 'accounts:global-search' %}">
        <div class="input-group input-group-sm">
          <input
            name="q"
            class="form-control form-control-navbar"
            type="search"
            placeholder="Search"
            aria-label="Search"
            value="{{ request.GET.q }}"
          >
          <div class="input-group-append">
            <button class="btn btn-navbar" type="submit">
              <i class="fas fa-search"></i>
            </button>
            <button class="btn btn-navbar" type="button"
                    onclick="this.closest('form').querySelector('input[name=q]').value=''">
              <i class="fas fa-times"></i>
            </button>
            <!-- <button class="btn btn-navbar" type="button" data-widget="navbar-search">
              <i class="fas fa-times"></i> -->
            </button>
          </div>
        </div>
      </form>
      <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#">
              <i class="far fa-bell"></i>
              {% if notification_count > 0 %}
                  <span class="badge badge-danger navbar-badge">{{ notification_count }}</span>
              {% endif %}
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
              <span class="dropdown-item dropdown-header">{{ notification_count }} Paziņojumi</span>
              <div class="dropdown-divider"></div>
              
              {% for n in latest_notifications %}
                  <a href="{% url 'notifications:notification-list' %}" class="dropdown-item">
                      <i class="fas fa-envelope mr-2"></i> {{ n.verb|truncatechars:30 }}
                  </a>
                  <div class="dropdown-divider"></div>
              {% empty %}
                  <span class="dropdown-item text-center text-muted">Nav jaunu paziņojumu</span>
              {% endfor %}
              
              <a href="{% url 'notifications:notification-list' %}" class="dropdown-item dropdown-footer">Skatīt visus</a>
          </div>
      </li>


         <!-- Profile Dropdown Menu -->
         <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#">
            <img class="img-circle elevation-2" src="{{ request.user.profile.profile_picture_url }}" height="30" width="30" alt="user picture">
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <span class="dropdown-item dropdown-header">Welcome, {{ request.user.profile.full_name }}</span>
            <div class="dropdown-divider"></div>
  
                <a href="{% url "accounts:profile-update" request.user.profile.pk %}" class="dropdown-item">
                  <i class="fas fa-cog mr-2"></i> Edit Profile
                </a>
                <div class="dropdown-divider"></div>

                <a href="{% url "accounts:password-change" %}" class="dropdown-item">
                  <i class="fas fa-lock mr-2"></i> Change Password
                </a>
                <div class="dropdown-divider"></div>

                <a href="{% url 'admin:index' %}" class="dropdown-item">
                  <i class="fas fa-lock mr-2"></i> Admin Panel
                </a>
                <div class="dropdown-divider"></div>

              <form action="{% url "logout" %}" method="post">
                {% csrf_token %}
                  <button  class="dropdown-item">
                    <i class="fas fa-sign-out-alt mr-2"></i> Logout
                  </button>
                  <div class="dropdown-divider"></div>
              </form>
                
         
  
            <a href="{% url "notifications:notification-list" %}" class="dropdown-item dropdown-footer">See All Notifications</a>
          </div>
        </li>



      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      
    </ul>
  </nav>

templates/components/paginator.html
   {% comment %} pagination controls {% endcomment %}
   <div class="pagination">  

    <span class="step-links">

        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

     <span class"current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
     </span>

     {% if page_obj.has_next %}
     <a href="?page={{ page_obj.next_page_number }}">next</a>
     <a href="?page={{ page_obj.paginator.num_pages }}">last</a>
     {% endif %}

    </span>
  </div>

templates/components/sidebar.html
{% load static %}

<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url "accounts:dashboard" %}" class="brand-link">
      <img src="{% static "dist/img/AdminLTELogo.png" %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Welcome!</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ request.user.profile.profile_picture_url }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{% url "accounts:profile-detail" request.user.profile.pk %}" class="d-block">{{ request.user.profile.full_name }}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <!-- <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div> -->

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

               <!-- Home -->
               <li class="nav-item">
                <a href="{% url "accounts:dashboard" %}" class="nav-link {% if request.resolver_match.url_name == 'dashboard'  %}active{% endif %} ">
                  <i class="nav-icon fas fa-chart-line"></i>
                  <p>Dashboard</p>
                </a>
              </li>

                <!-- Projects -->
              <li class="nav-item">
                <a href="#" class="nav-link {% if request.resolver_match.app_name == 'projects' %}active{% endif %}">
                  <i class="nav-icon fas fa-project-diagram"></i>
                  <p>
                    Projects
                    <i class="fas fa-angle-left right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'projects:list' %}" class="nav-link {% if request.resolver_match.app_name == 'projects' and request.resolver_match.url_name == 'list' %}active{% endif %}">
                      <i class="far fa-circle nav-icon text-danger"></i>
                      <p>All Projects</p>
                    </a>
                  </li>
                  <li class="nav-item">
                      <a href="{% url 'projects:my-projects' %}" class="nav-link {% if request.resolver_match.url_name == 'my-projects' %}active{% endif %}">
                          <i class="far fa-circle nav-icon text-warning"></i>
                          <p>My Projects</p>
                      </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'projects:create' %}" class="nav-link {% if request.resolver_match.app_name == 'projects' and request.resolver_match.url_name == 'create' %}active{% endif %}">
                      <i class="far fa-circle nav-icon text-info"></i>
                      <p>Add Project</p>
                    </a>
                  </li>
                </ul>
              </li>
              <!-- Teams -->
              <li class="nav-item">
                <a href="#" class="nav-link {% if request.resolver_match.url_name == 'team-create'  or request.resolver_match.url_name == 'team-list' %}active{% endif %}">
                  <i class="nav-icon fas fa-users"></i>
                  <p>
                    Teams
                    <i class="fas fa-angle-left right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url "teams:team-list" %}" class="nav-link {% if request.resolver_match.url_name == 'team-list' %}active{% endif %}">
                      <i class="far fa-circle nav-icon text-danger"></i>
                      <p>All Teams</p>
                    </a>
                  </li>

                  <li class="nav-item">
                    <a href="{% url 'teams:my-teams' %}" class="nav-link {% if request.resolver_match.url_name == 'my-teams' %}active{% endif %}">
                      <i class="far fa-circle nav-icon text-warning"></i>
                      <p>My Teams</p>
                    </a>
                  </li>

                  <li class="nav-item">
                    <a href="{% url "teams:team-create" %}" class="nav-link {% if request.resolver_match.url_name == 'team-create' %}active{% endif %}">
                      <i class="far fa-circle nav-icon text-info"></i>
                      <p>Add Teams</p>
                    </a>
                  </li>
                </ul>
              </li>

              <!-- Tasks -->

              <li class="nav-item">
                <a href="#" class="nav-link {% if request.resolver_match.app_name == 'tasks' %}active{% endif %}">
                  <i class="nav-icon fas fa-tasks"></i>
                  <p>
                    Tasks
                    <i class="fas fa-angle-left right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'tasks:list' %}" class="nav-link {% if request.resolver_match.app_name == 'tasks' and request.resolver_match.url_name == 'list' %}active{% endif %}">
                      <i class="far fa-circle nav-icon text-danger"></i>
                      <p>All Tasks</p>
                    </a>
                  </li>
                  <li class="nav-item">
                      <a href="{% url 'tasks:my-active-tasks' %}" class="nav-link {% if request.resolver_match.url_name == 'my-active-tasks' %}active{% endif %}">
                          <i class="far fa-circle nav-icon text-warning"></i>
                          <p>My Active Tasks</p>
                      </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'tasks:active-tasks' %}" class="nav-link {% if request.resolver_match.url_name == 'active-tasks' %}active{% endif %}">
                      <i class="far fa-circle nav-icon text-info"></i>
                      <p>Active Tasks</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'tasks:create' %}" class="nav-link {% if request.resolver_match.app_name == 'tasks' and request.resolver_match.url_name == 'create' %}active{% endif %}">
                      <i class="far fa-circle nav-icon text-success"></i>
                      <p>New Task</p>
                    </a>
                  </li>
                </ul>
              </li>
              <!-- Archive -->
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon fas fa-archive"></i> <p>
                    Archive
                    <i class="fas fa-angle-left right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'projects:archive-projects' %}" class="nav-link {% if request.resolver_match.url_name == 'archive-projects' %}active{% endif %}">
                      <i class="far fa-circle nav-icon text-danger"></i>
                      <p>Archive Projects</p>
                    </a>
                  </li>
                  <li class="nav-item">
                      <a href="{% url 'tasks:archive-tasks' %}" class="nav-link {% if request.resolver_match.url_name == 'archive-tasks' %}active{% endif %}">
                          <i class="far fa-circle nav-icon text-warning"></i>
                          <p>Archive Tasks</p>
                      </a>
                  </li>
                </ul>
              </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>